// source: sql_type.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.duckdb_webapi.proto.SQLType', null, global);
goog.exportSymbol('proto.duckdb_webapi.proto.SQLTypeID', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.duckdb_webapi.proto.SQLType = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.duckdb_webapi.proto.SQLType, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.duckdb_webapi.proto.SQLType.displayName = 'proto.duckdb_webapi.proto.SQLType';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.duckdb_webapi.proto.SQLType.prototype.toObject = function(opt_includeInstance) {
  return proto.duckdb_webapi.proto.SQLType.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.duckdb_webapi.proto.SQLType} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.duckdb_webapi.proto.SQLType.toObject = function(includeInstance, msg) {
  var f, obj = {
    typeId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    width: jspb.Message.getFieldWithDefault(msg, 2, 0),
    scale: jspb.Message.getFieldWithDefault(msg, 3, 0),
    collation: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.duckdb_webapi.proto.SQLType}
 */
proto.duckdb_webapi.proto.SQLType.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.duckdb_webapi.proto.SQLType;
  return proto.duckdb_webapi.proto.SQLType.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.duckdb_webapi.proto.SQLType} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.duckdb_webapi.proto.SQLType}
 */
proto.duckdb_webapi.proto.SQLType.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.duckdb_webapi.proto.SQLTypeID} */ (reader.readEnum());
      msg.setTypeId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setWidth(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setScale(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setCollation(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.duckdb_webapi.proto.SQLType.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.duckdb_webapi.proto.SQLType.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.duckdb_webapi.proto.SQLType} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.duckdb_webapi.proto.SQLType.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTypeId();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getWidth();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getScale();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getCollation();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional SQLTypeID type_id = 1;
 * @return {!proto.duckdb_webapi.proto.SQLTypeID}
 */
proto.duckdb_webapi.proto.SQLType.prototype.getTypeId = function() {
  return /** @type {!proto.duckdb_webapi.proto.SQLTypeID} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.duckdb_webapi.proto.SQLTypeID} value
 * @return {!proto.duckdb_webapi.proto.SQLType} returns this
 */
proto.duckdb_webapi.proto.SQLType.prototype.setTypeId = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional uint32 width = 2;
 * @return {number}
 */
proto.duckdb_webapi.proto.SQLType.prototype.getWidth = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.duckdb_webapi.proto.SQLType} returns this
 */
proto.duckdb_webapi.proto.SQLType.prototype.setWidth = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint32 scale = 3;
 * @return {number}
 */
proto.duckdb_webapi.proto.SQLType.prototype.getScale = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.duckdb_webapi.proto.SQLType} returns this
 */
proto.duckdb_webapi.proto.SQLType.prototype.setScale = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string collation = 4;
 * @return {string}
 */
proto.duckdb_webapi.proto.SQLType.prototype.getCollation = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.duckdb_webapi.proto.SQLType} returns this
 */
proto.duckdb_webapi.proto.SQLType.prototype.setCollation = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * @enum {number}
 */
proto.duckdb_webapi.proto.SQLTypeID = {
  SQL_INVALID: 0,
  SQL_NULL: 1,
  SQL_UNKNOWN: 2,
  SQL_ANY: 3,
  SQL_BOOLEAN: 10,
  SQL_TINYINT: 11,
  SQL_SMALLINT: 12,
  SQL_INTEGER: 13,
  SQL_BIGINT: 14,
  SQL_DATE: 15,
  SQL_TIME: 16,
  SQL_TIMESTAMP: 17,
  SQL_FLOAT: 18,
  SQL_DOUBLE: 19,
  SQL_DECIMAL: 20,
  SQL_CHAR: 21,
  SQL_VARCHAR: 22,
  SQL_VARBINARY: 23,
  SQL_BLOB: 24,
  SQL_STRUCT: 100,
  SQL_LIST: 101
};

goog.object.extend(exports, proto.duckdb_webapi.proto);
