include(FindPythonInterp)

set(DUCKDB_SOURCE_DIR "${CMAKE_SOURCE_DIR}/../submodules/duckdb/")
set(DUCKDB_AMALGAMATION_DIR "${DUCKDB_SOURCE_DIR}/src/amalgamation/")
set(DUCKDB_INCLUDE_DIR "${DUCKDB_AMALGAMATION_DIR}")
set(DUCKDB_HEADER_FILE "${DUCKDB_AMALGAMATION_DIR}/duckdb.hpp")
set(DUCKDB_SOURCE_FILE "${DUCKDB_AMALGAMATION_DIR}/duckdb.cpp")

add_custom_command(
    OUTPUT ${DUCKDB_HEADER_FILE} ${DUCKDB_SOURCE_FILE}
    WORKING_DIRECTORY ${DUCKDB_SOURCE_DIR}
    COMMAND ${PYTHON_EXECUTABLE} ./scripts/amalgamation.py
)
